# Generated by Django 5.2.17 on 2026-08-29 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('game_type', models.CharField(default='free_fire', max_length=20)),
                ('match_type', models.CharField(choices=[('squad_br', 'Full Map Battle Royale (Squad)'), ('clash_squad', 'Clash Squad (4v4 CS)'), ('solo_br', 'Solo Full Map BR'), ('duo_br', 'Duo Full Map BR')], default='clash_squad', max_length=30)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('description', models.TextField(blank=True)),
                ('room_id', models.CharField(blank=True, help_text='Custom Room ID (Revealed to participants)', max_length=50)),
                ('room_password', models.CharField(blank=True, help_text='Room Password', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('prize_pool', models.CharField(default='Campus Glory & Winner Badge 🏆', max_length=100)),
                ('entry_fee', models.CharField(default='FREE', max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming Match'), ('live', 'Match Live Now 🔥'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('max_teams', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='GamingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('free_fire', 'Free Fire MAX / Free Fire'), ('bgmi', 'BGMI / PUBG Mobile')], default='free_fire', max_length=20)),
                ('uid', models.CharField(db_index=True, max_length=32)),
                ('in_game_name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('br_rank', models.CharField(default='Platinum', max_length=50)),
                ('br_rank_points', models.PositiveIntegerField(default=1000)),
                ('cs_rank', models.CharField(default='Gold', max_length=50)),
                ('kd_ratio', models.FloatField(default=1.0)),
                ('total_booyahs', models.PositiveIntegerField(default=0)),
                ('headshot_rate', models.FloatField(default=0.0)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(default='IND', max_length=20)),
                ('proof_screenshot', models.ImageField(blank=True, null=True, upload_to='gaming_proofs/')),
                ('is_verified', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaming_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
