# Generated by Django 5.2.17 on 2026-09-04 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. HostelTalkies BGMI Championship, Free Fire MAX Weekend Clash', max_length=200)),
                ('game', models.CharField(choices=[('bgmi', 'BGMI'), ('bgmi_lite', 'BGMI Lite'), ('free_fire_max', 'Free Fire MAX'), ('other', 'Other Game')], default='bgmi', max_length=50)),
                ('custom_game_name', models.CharField(blank=True, default='', help_text="Game name if 'Other' is selected", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Overview and details of the competition')),
                ('rules', models.TextField(blank=True, default='', help_text='Competition rules, device restrictions, screenshot proof requirements')),
                ('competition_type', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('squad', 'Squad'), ('1v1', '1v1 Match'), ('team', 'Team vs Team'), ('custom', 'Custom Format')], default='squad', max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('live', 'Live / In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registration_open', max_length=30)),
                ('start_datetime', models.DateTimeField(help_text='Match / Tournament start date and time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Expected end date and time', null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Deadline to join', null=True)),
                ('max_participants', models.PositiveIntegerField(default=50, help_text='Maximum players/slots allowed')),
                ('is_registration_closed_by_organizer', models.BooleanField(default=False)),
                ('room_id', models.CharField(blank=True, default='', help_text='In-game Custom Room ID', max_length=100)),
                ('room_password', models.CharField(blank=True, default='', help_text='In-game Room Password', max_length=100)),
                ('scoring_type', models.CharField(choices=[('manual', 'Manual Organizer Entry'), ('participant_submission', 'Participant Submission + Organizer Verification'), ('points_based', 'Points-Based (Kills + Placement)')], default='participant_submission', max_length=30)),
                ('scoring_rules', models.JSONField(blank=True, default=dict, help_text='Custom points configuration e.g. points per kill and placement points')),
                ('prize_pool', models.CharField(blank=True, default='', help_text='Prizes, trophies or bragging rights', max_length=200)),
                ('contact_info', models.CharField(blank=True, default='', help_text='Host WhatsApp group / Room number / Discord', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaming_competitions', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-start_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(help_text="Player's in-game nickname/IGN", max_length=100)),
                ('game_uid', models.CharField(blank=True, default='', help_text='Informational player UID (no API fetch)', max_length=100)),
                ('team_name', models.CharField(blank=True, default='', help_text='Team or Clan name if applicable', max_length=150)),
                ('team_members', models.TextField(blank=True, default='', help_text='Teammates / roster details')),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('slot_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('disqualified', 'Disqualified')], default='registered', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gaming.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('competition', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, help_text='Final placement rank e.g. 1, 2, 3', null=True)),
                ('kills', models.PositiveIntegerField(default=0, help_text='Number of kills')),
                ('points', models.FloatField(default=0.0, help_text='Calculated or assigned points')),
                ('score', models.CharField(blank=True, default='', help_text="Match score or outcome e.g. 'Won 16-10', 'Booyah'", max_length=100)),
                ('proof_image', models.ImageField(blank=True, help_text='Screenshot proof of match result', null=True, upload_to='gaming/proofs/')),
                ('notes', models.TextField(blank=True, default='', help_text='Submission notes or comments')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gaming.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gaming.competitionparticipant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', 'position', '-kills', '-submitted_at'],
            },
        ),
    ]
