# Generated by Django 5.2.17 on 2026-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted / Active Borrow'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='tag', help_text='Icon identifier e.g. bicycle, laptop, book, shirt', max_length=50)),
                ('post_type', models.CharField(choices=[('all', 'All Post Types'), ('marketplace', 'Buy, Sell, Giveaway, Exchange, Borrow'), ('lost_found', 'Lost & Found'), ('study', 'Study & Academics'), ('services', 'Hostel Services'), ('roommate', 'Room / Roommate'), ('general', 'General Community')], default='all', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('buy_sell', 'Buy & Sell'), ('giveaway', 'Giveaway (Free)'), ('exchange', 'Exchange / Barter'), ('borrow', 'Borrow Request'), ('lend', 'Lend Offer'), ('lost', 'Lost Item'), ('found', 'Found Item'), ('roommate', 'Room / Roommate'), ('study', 'Study Discussion'), ('help', 'Help / Query'), ('service', 'Service Announcement'), ('general', 'General Talkies')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty or 0 for free/giveaway/lost items', max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New / Barely Used'), ('good', 'Good Condition'), ('used', 'Used / Fair'), ('na', 'Not Applicable')], default='na', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available / Open'), ('sold', 'Sold / Taken'), ('closed', 'Closed / Resolved')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('event_date', models.DateField(blank=True, help_text='Date when item was lost/found or needed', null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
