# Generated by Django 5.2.17 on 2026-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('buy_sell', 'Buy & Sell'), ('giveaway', 'Giveaway (Free)'), ('exchange', 'Exchange / Barter'), ('borrow', 'Borrow Request'), ('lend', 'Lend Offer'), ('lost', 'Lost Item'), ('found', 'Found Item'), ('roommate', 'Room / Roommate'), ('study', 'Study Discussion'), ('help', 'Help / Query'), ('service', 'Service Announcement'), ('general', 'General Talkies'), ('others', 'Others')], default='general', max_length=30),
        ),
    ]
