# Generated by Django on 2026-09-08

from django.db import migrations


def normalize_category_post_types(apps, schema_editor):
    Category = apps.get_model('posts', 'Category')

    for cat in Category.objects.all():
        name_lower = cat.name.strip().lower()
        if any(w in name_lower for w in ['roommate', 'accommodation', 'room & roommate']):
            cat.post_type = 'roommate'
        elif any(w in name_lower for w in ['lost & found', 'lost and found', 'lost item', 'found item']):
            cat.post_type = 'lost_found'
        elif any(w in name_lower for w in ['general campus', 'campus talkies', 'general talkies', 'general discussion']):
            cat.post_type = 'general'
        elif 'hostel services' in name_lower or 'campus services' in name_lower:
            cat.post_type = 'services'
        elif 'study notes' in name_lower and 'desk' not in name_lower:
            cat.post_type = 'study'
        else:
            cat.post_type = 'marketplace'
        cat.save(update_fields=['post_type'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.RunPython(normalize_category_post_types, reverse_noop),
    ]
