# Generated by Django 6.0.7 on 2026-08-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WardenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('is_approved', models.BooleanField(default=True, help_text='Chief Admin approval status')),
                ('is_verified', models.BooleanField(default=False, help_text='Email OTP verification status')),
                ('otp_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('can_view_students', models.BooleanField(default=True, help_text='Permission to view students in assigned hostel')),
                ('can_manage_notices', models.BooleanField(default=True, help_text='Permission to post and manage hostel notices')),
                ('can_manage_events', models.BooleanField(default=True, help_text='Permission to create and manage hostel events')),
                ('can_view_reports', models.BooleanField(default=True, help_text='Permission to view complaints and reports in assigned hostel')),
                ('can_manage_lost_found', models.BooleanField(default=True, help_text='Permission to moderate Lost & Found items in assigned hostel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardens', to='hostels.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warden_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
