# Generated by Django 5.2.17 on 2026-08-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
        ('users', '0003_student_warden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='hostels.hostel'),
        ),
        migrations.AlterField(
            model_name='wardenprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wardens', to='hostels.hostel'),
        ),
    ]
