# Generated by Django 5.2.17 on 2026-08-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentprofile_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardenprofile',
            name='can_manage_events',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='can_manage_lost_found',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='can_manage_notices',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='can_view_students',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='otp_hash',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='otp_last_sent_at',
        ),
    ]
