# Generated by Django 5.2.17 on 2026-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_wardenprofile_can_manage_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, default='', help_text='Branch / Specialisation', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='programme',
            field=models.CharField(blank=True, default='', help_text='Course / Programme e.g. B.Tech, BCA, MCA', max_length=50),
        ),
    ]
