# Generated by Django 5.2.17 on 2026-08-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_branch_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardenprofile',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='wardenprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Warden',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_warden',
        ),
        migrations.DeleteModel(
            name='WardenProfile',
        ),
    ]
