# Generated by Django 5.2.17 on 2026-08-20 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='Leave blank for campus-wide events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='hostels.hostel'),
        ),
    ]
