# Generated by Django for HostelTalkies
from django.db import migrations
from datetime import date, time

def add_sih_2026_event(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    title = 'Smart India Hackathon (SIH) 2026 – Internal Round'
    description = (
        "Smart India Hackathon (SIH) 2026 – Internal Round is organized under the aegis of the "
        "Institution’s Innovation Council (IIC), VBSPU. Students are encouraged to participate actively "
        "in this prestigious national-level innovation and problem-solving platform to develop innovative technological solutions.\n\n"
        "🔥 IMPORTANT DATES:\n"
        "• Problem Statements Released: 21 August 2026\n"
        "• PPT Submission Deadline: 12 September 2026\n"
        "• Final Hackathon: 15 September 2026\n\n"
        "👥 PARTICIPATION GUIDELINES:\n"
        "• Team Size: 6 Members\n"
        "• Mandatory: At least 1 female member is mandatory in each team\n"
        "• Students of Faculty of Engineering and Technology (UNSIET) are especially encouraged to participate.\n\n"
        "🚀 REGISTRATION & CONTACT:\n"
        "• Registration Link: https://forms.gle/YLZTDtHaQTDESos7\n"
        "• Registration/Enquiry: usatym2508@gmail.com\n\n"
        "COORDINATOR:\n"
        "Dr. Satyam Kumar Upadhyay (SPOC-SIH-2026 & Coordinator)\n\n"
        "IIC PRESIDENT:\n"
        "Prof. Rajnish Bhasker (IIC President, VBSPU)"
    )

    event, created = Event.objects.get_or_create(
        title=title,
        defaults={
            'description': description,
            'event_date': date(2026, 9, 15),
            'event_time': time(9, 0),
            'location': 'Faculty of Engineering and Technology (UNSIET), VBS Purvanchal University, Jaunpur',
            'hostel': None,  # Public / campus-wide for ALL hostels and students
            'organizer': 'Institution’s Innovation Council (IIC), UNSIET, VBSPU',
            'banner_image': 'events/sih-2026-notice.jpg',
            'is_active': True,
        }
    )
    if not created:
        event.description = description
        event.event_date = date(2026, 9, 15)
        event.event_time = time(9, 0)
        event.location = 'Faculty of Engineering and Technology (UNSIET), VBS Purvanchal University, Jaunpur'
        event.hostel = None
        event.organizer = 'Institution’s Innovation Council (IIC), UNSIET, VBSPU'
        event.banner_image = 'events/sih-2026-notice.jpg'
        event.is_active = True
        event.save()


def remove_sih_2026_event(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(title='Smart India Hackathon (SIH) 2026 – Internal Round').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created_by'),
    ]

    operations = [
        migrations.RunPython(add_sih_2026_event, reverse_code=remove_sih_2026_event),
    ]
