# Generated by Django 5.2.17 on 2026-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(choices=[('notes', 'Lecture Notes & Summaries'), ('book', 'E-Book / Reference Book'), ('pyq', 'Previous Year Questions (PYQ)'), ('pdf', 'Handout / Cheat Sheet (PDF)'), ('assignment', 'Assignments & Solutions'), ('study_group', 'Study Group / Peer Learning')], default='notes', max_length=30)),
                ('course_name', models.CharField(help_text='e.g. Data Structures, Thermodynamics', max_length=150)),
                ('course_code', models.CharField(blank=True, default='', help_text='e.g. CS201, ME302', max_length=50)),
                ('semester', models.CharField(blank=True, default='', help_text='e.g. Sem 1, Sem 2, etc.', max_length=20)),
                ('department', models.CharField(blank=True, default='', help_text='e.g. Computer Science, Mechanical', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_resources/')),
                ('external_link', models.URLField(blank=True, default='')),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
