# Generated by Django 5.2.17 on 2026-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Faculty or Contributor Name', max_length=150),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='is_pending_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='source_website',
            field=models.CharField(blank=True, default='', help_text='e.g. VBSPU PYQ Hub / VbspuEDU', max_length=255),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='e.g. Unit 1, Unit 2, All Units', max_length=50),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='resource_type',
            field=models.CharField(choices=[('notes', 'Lecture Notes & Summaries'), ('book', 'E-Book / Reference Book'), ('pyq', 'Previous Year Questions (PYQ)'), ('pdf', 'Handout / Cheat Sheet (PDF)'), ('assignment', 'Assignments & Solutions'), ('study_group', 'Study Group / Peer Learning'), ('syllabus', 'Syllabus & Curriculum'), ('lab_file', 'Lab Manuals & Practical Files')], default='notes', max_length=30),
        ),
    ]
