# Generated by Django 5.2.17 on 2026-09-04 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studyresource_author_studyresource_is_pending_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flagged when automatic classification is uncertain. Admin should verify.'),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='department',
            field=models.CharField(blank=True, default='', help_text='e.g. Computer Science (CSE)', max_length=100),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='is_pending_review',
            field=models.BooleanField(default=False, help_text='Held from public view pending admin approval.'),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='resource_type',
            field=models.CharField(choices=[('notes', 'Lecture Notes & Summaries'), ('pyq', 'Previous Year Questions (PYQ)'), ('important_questions', 'Important Questions'), ('study_material', 'Study Material'), ('syllabus', 'Syllabus & Curriculum'), ('lab_file', 'Lab Manuals & Practical Files'), ('reference_material', 'Reference Material / E-Book'), ('pdf', 'Handout / Cheat Sheet (PDF)'), ('assignment', 'Assignments & Solutions'), ('other', 'Other Academic Resource')], default='notes', max_length=30),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='semester',
            field=models.CharField(blank=True, default='', help_text='e.g. Sem 1, Sem 3', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Internal: original source page URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='source_website',
            field=models.CharField(blank=True, default='', help_text='Internal: e.g. VBSPU PYQ Hub / VbspuEDU', max_length=255),
        ),
        migrations.AddIndex(
            model_name='studyresource',
            index=models.Index(fields=['semester', 'department', 'course_name'], name='study_study_semeste_8f39dc_idx'),
        ),
        migrations.AddIndex(
            model_name='studyresource',
            index=models.Index(fields=['resource_type'], name='study_study_resourc_534f62_idx'),
        ),
        migrations.AddIndex(
            model_name='studyresource',
            index=models.Index(fields=['is_active', 'needs_review'], name='study_study_is_acti_376420_idx'),
        ),
    ]
