# Generated by Django 5.2.17 on 2026-09-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_add_new_resource_types_and_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='exam_session',
            field=models.CharField(blank=True, default='', help_text='Exam session, e.g. Regular, Back Paper, S1, S2, Odd Sem, Even Sem', max_length=50),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='year',
            field=models.CharField(blank=True, default='', help_text='Academic / Exam Year, e.g. 2025, 2024', max_length=20),
        ),
    ]
