# Generated by Django 5.2.17 on 2026-09-06 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_studyresource_exam_session_studyresource_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studyresource',
            index=models.Index(fields=['is_active', 'is_pending_review', 'resource_type'], name='study_study_is_acti_8cccc0_idx'),
        ),
        migrations.AddIndex(
            model_name='studyresource',
            index=models.Index(fields=['is_active', 'is_pending_review', 'course_name'], name='study_study_is_acti_de2e3c_idx'),
        ),
    ]
