# Generated by Django 5.2.17 on 2026-08-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('laundry', 'Laundry & Ironing'), ('printing', 'Printing & Photocopy'), ('repair', 'Repairs & Electrician'), ('barber', 'Barber & Grooming'), ('tailor', 'Tailoring'), ('cleaning', 'Cleaning & Housekeeping'), ('canteen', 'Canteen & Mess'), ('other', 'Other Essential Service')], default='other', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(help_text='e.g. Ground floor Block B, Near Main Gate', max_length=150)),
                ('timings', models.CharField(help_text='e.g. 9:00 AM - 8:00 PM (Daily)', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='hostels.hostel')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
