# Generated by Django 5.2.17 on 2026-08-20 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_block',
            field=models.ForeignKey(blank=True, help_text='Optional block targeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='hostels.block'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_hostel',
            field=models.ForeignKey(blank=True, help_text='Leave empty to target all hostels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='hostels.hostel'),
        ),
    ]
