# Generated by Django for HostelTalkies
from django.db import migrations

def add_new_hostels(apps, schema_editor):
    Hostel = apps.get_model('hostels', 'Hostel')
    Block = apps.get_model('hostels', 'Block')
    Room = apps.get_model('hostels', 'Room')

    hostels_to_add = [
        {
            'name': 'Meerabai Hostel',
            'code': 'MEERABAI-HOSTEL',
            'gender': 'girls',
            'description': 'Girls hostel for students.',
        },
        {
            'name': 'Lakshmibai Hostel',
            'code': 'LAKSHMIBAI-HOSTEL',
            'gender': 'girls',
            'description': 'Girls hostel for students.',
        },
        {
            'name': 'Draupadi Hostel',
            'code': 'DRAUPADI-HOSTEL',
            'gender': 'girls',
            'description': 'Girls hostel for students.',
        },
        {
            'name': 'Srinivas Ramanujan PG Hostel',
            'code': 'SRPG-HOSTEL',
            'gender': 'boys',
            'description': 'Boys hostel for students.',
        },
    ]

    for h_data in hostels_to_add:
        hostel, created = Hostel.objects.get_or_create(
            name=h_data['name'],
            defaults={
                'code': h_data['code'],
                'gender': h_data['gender'],
                'description': h_data['description'],
                'is_active': True,
            }
        )
        if not created:
            updated = False
            if not hostel.description:
                hostel.description = h_data['description']
                updated = True
            if hostel.gender != h_data['gender']:
                hostel.gender = h_data['gender']
                updated = True
            if updated:
                hostel.save()

        # Seed standard blocks and rooms for consistency
        for b_name in ['Block A', 'Block B', 'Block C']:
            block, _ = Block.objects.get_or_create(hostel=hostel, name=b_name)
            for r_num in ['101', '102', '103', '201', '202']:
                Room.objects.get_or_create(block=block, room_number=r_num)


def remove_new_hostels(apps, schema_editor):
    Hostel = apps.get_model('hostels', 'Hostel')
    names = [
        'Meerabai Hostel',
        'Lakshmibai Hostel',
        'Draupadi Hostel',
        'Srinivas Ramanujan PG Hostel',
    ]
    Hostel.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_new_hostels, reverse_code=remove_new_hostels),
    ]
