# Generated by Django 5.2.17 on 2026-08-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_deleted_for_users_message_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_type', models.CharField(choices=[('default', 'Default Pattern'), ('solid', 'Solid Color'), ('gradient', 'Gradient'), ('wallpaper', 'Pattern/Wallpaper'), ('custom', 'Custom Photo/Image')], default='default', max_length=20)),
                ('bg_value', models.CharField(blank=True, default='', max_length=255)),
                ('custom_bg_image', models.ImageField(blank=True, null=True, upload_to='chat_backgrounds/%Y/%m/')),
                ('bubble_style', models.CharField(choices=[('classic', 'Classic'), ('rounded', 'Rounded'), ('minimal', 'Minimal'), ('compact', 'Compact')], default='classic', max_length=20)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customizations', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
