# Generated by Django 5.2.17 on 2026-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('post', 'Post / Listing'), ('user', 'User Account'), ('comment', 'Comment')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('spam', 'Spam or Commercial promotion'), ('fake_listing', 'Fake or Misleading listing'), ('scam', 'Scam or Fraudulent attempt'), ('harassment', 'Harassment or Inappropriate behavior'), ('inappropriate_content', 'Inappropriate or Offensive content'), ('other', 'Other Reason')], max_length=40)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'In Review'), ('resolved', 'Resolved / Action Taken'), ('dismissed', 'Dismissed / No Violation')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='HostelTalkies', max_length=100)),
                ('tagline', models.CharField(default='Your Hostel. Your People. Your Talkies.', max_length=255)),
                ('community_rules', models.TextField(blank=True, default='1. Be respectful\n2. Genuine student listings only\n3. Protect hostel property and privacy.')),
                ('guidelines', models.TextField(blank=True, default='Guidelines for posting, trading, and community conduct.')),
                ('contact_email', models.EmailField(default='support@hosteltalkies.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
